export const ERROR_CODES = {
  AUTO_TRANSLATION_DISABLED: 'AUTO_TRANSLATION_DISABLED',
  BASE_LOCALE_IMMUTABLE: 'BASE_LOCALE_IMMUTABLE',
  BUNDLE_ALREADY_EXISTS: 'BUNDLE_ALREADY_EXISTS',
  BUNDLE_NOT_FOUND: 'BUNDLE_NOT_FOUND',
  CANNOT_TRANSLATE_BASE_LOCALE: 'CANNOT_TRANSLATE_BASE_LOCALE',
  COLLECTION_ALREADY_EXISTS: 'COLLECTION_ALREADY_EXISTS',
  COLLECTION_BASE_LOCALE_MISMATCH: 'COLLECTION_BASE_LOCALE_MISMATCH',
  COLLECTION_NOT_FOUND: 'COLLECTION_NOT_FOUND',
  COLLECTION_READ_ONLY: 'COLLECTION_READ_ONLY',
  COLLECTION_RENAME_BUNDLE_CONFLICT: 'COLLECTION_RENAME_BUNDLE_CONFLICT',
  COLLECTION_REQUIRED_BY_BUNDLE: 'COLLECTION_REQUIRED_BY_BUNDLE',
  CONFIG_CHANGED: 'CONFIG_CHANGED',
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_PARSE_FAILED: 'CONFIG_PARSE_FAILED',
  CORE_OPERATION_ERROR: 'CORE_OPERATION_ERROR',
  FOLDER_MOVE_INTO_DESCENDANT: 'FOLDER_MOVE_INTO_DESCENDANT',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',
  GLOSSARY_EXTRACTOR_ERROR: 'GLOSSARY_EXTRACTOR_ERROR',
  GLOSSARY_NO_COLLECTIONS: 'GLOSSARY_NO_COLLECTIONS',
  IMPORT_SOURCE_ERROR: 'IMPORT_SOURCE_ERROR',
  INVALID_BUNDLE_DEFINITION: 'INVALID_BUNDLE_DEFINITION',
  INVALID_BUNDLE_LOCALES: 'INVALID_BUNDLE_LOCALES',
  INVALID_COLLECTION: 'INVALID_COLLECTION',
  INVALID_COLLECTION_FOLDER: 'INVALID_COLLECTION_FOLDER',
  INVALID_CONFIG: 'INVALID_CONFIG',
  INVALID_FOLDER_PATH: 'INVALID_FOLDER_PATH',
  INVALID_IMPORT_LOCALE: 'INVALID_IMPORT_LOCALE',
  INVALID_LOCALE: 'INVALID_LOCALE',
  INVALID_NAME: 'INVALID_NAME',
  INVALID_PREFERRED_TERMINOLOGY: 'INVALID_PREFERRED_TERMINOLOGY',
  INVALID_PROJECT_TERMS_EDIT: 'INVALID_PROJECT_TERMS_EDIT',
  INVALID_PROTECTED_TERMS_FILE: 'INVALID_PROTECTED_TERMS_FILE',
  INVALID_RESOURCE_KEY: 'INVALID_RESOURCE_KEY',
  INVALID_TRANSLATION_STATUS: 'INVALID_TRANSLATION_STATUS',
  LOCALE_ALREADY_EXISTS: 'LOCALE_ALREADY_EXISTS',
  LOCALE_NOT_FOUND: 'LOCALE_NOT_FOUND',
  MULTIPLE_BUNDLE_CONSTANT_NAME: 'MULTIPLE_BUNDLE_CONSTANT_NAME',
  NO_TRANSLATION_TARGET_LOCALES: 'NO_TRANSLATION_TARGET_LOCALES',
  PARENT_DIRECTORY_MISSING: 'PARENT_DIRECTORY_MISSING',
  PROTECTED_TERMS_FILE_NOT_SET: 'PROTECTED_TERMS_FILE_NOT_SET',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  TRANSLATION_LOCALE_NOT_CONFIGURED: 'TRANSLATION_LOCALE_NOT_CONFIGURED',
} as const;

export type DomainErrorCode = keyof typeof ERROR_CODES;

/** Codes core's providers raise today; the taxonomy stays open (see ProviderErrorCode). */
export const PROVIDER_ERROR_CODES = [
  'AUTH_ERROR',
  'INVALID_REQUEST',
  'INVALID_REQUEST_TIMEOUT',
  'INVALID_RESPONSE',
  'MISSING_API_KEY',
  'RATE_LIMIT',
  'SERVER_ERROR',
  'TIMEOUT',
  'UNKNOWN_PROVIDER',
] as const;

export type KnownProviderErrorCode = (typeof PROVIDER_ERROR_CODES)[number];
export type ProviderErrorCode = KnownProviderErrorCode | (string & {});

/** Closed set the API table must cover. */
export type ErrorCode = DomainErrorCode | KnownProviderErrorCode;
