// Typed core errors. Callers map them by class (the API's exception filter, the CLI's reporter).

export type { FolderPathPart } from './error-messages';
export type { ErrorKind } from './lingo-tracker-error';
export {
  AutoTranslationDisabledError,
  BaseLocaleImmutableError,
  BundleAlreadyExistsError,
  BundleNotFoundError,
  CannotTranslateBaseLocaleError,
  CollectionAlreadyExistsError,
  CollectionBaseLocaleMismatchError,
  CollectionNotFoundError,
  CollectionRenameBundleConflictError,
  CollectionRequiredByBundleError,
  ConfigChangedError,
  ConfigNotFoundError,
  ConfigParseError,
  FolderMoveIntoDescendantError,
  FolderNotFoundError,
  ImportSourceError,
  InvalidBundleDefinitionError,
  InvalidBundleLocalesError,
  InvalidCollectionError,
  InvalidConfigError,
  InvalidFolderPathError,
  InvalidImportLocaleError,
  InvalidLocaleError,
  InvalidProjectTermsEditError,
  InvalidResourceKeyError,
  InvalidTranslationStatusError,
  LingoTrackerError,
  LocaleAlreadyExistsError,
  LocaleNotFoundError,
  MultipleBundleConstantNameError,
  ParentDirectoryMissingError,
  ProtectedTermsFileError,
  ProtectedTermsFileNotSetError,
  ReadOnlyCollectionError,
  ResourceAlreadyExistsError,
  ResourceNotFoundError,
  TranslationLocaleNotConfiguredError,
} from './lingo-tracker-error';
