// Typed core errors. Callers map them by class (the API's exception filter, the CLI's reporter).

export type { FolderPathPart } from './error-messages';
export {
  AutoTranslationDisabledError,
  BaseLocaleImmutableError,
  CannotTranslateBaseLocaleError,
  BundleAlreadyExistsError,
  BundleNotFoundError,
  CollectionAlreadyExistsError,
  CollectionNotFoundError,
  ConfigNotFoundError,
  ConfigParseError,
  FolderMoveIntoDescendantError,
  FolderNotFoundError,
  InvalidBundleDefinitionError,
  InvalidBundleLocalesError,
  InvalidCollectionError,
  InvalidConfigError,
  InvalidFolderPathError,
  ImportSourceError,
  InvalidImportLocaleError,
  InvalidLocaleError,
  InvalidResourceKeyError,
  LingoTrackerError,
  LocaleAlreadyExistsError,
  LocaleNotFoundError,
  TranslationLocaleNotConfiguredError,
  ParentDirectoryMissingError,
  ProtectedTermsFileError,
  ProtectedTermsFileNotSetError,
  ReadOnlyCollectionError,
  ResourceAlreadyExistsError,
  ResourceNotFoundError,
} from './lingo-tracker-error';
