export { ERROR_CODES, PROVIDER_ERROR_CODES } from './error-codes';
export type { DomainErrorCode, ErrorCode, KnownProviderErrorCode, ProviderErrorCode } from './error-codes';
// Core errors declare domain kinds and details; adapters own presentation.

export type { FolderPathPart } from './error-messages';
export type { CollectionTagEditProblem, ErrorKind } from './lingo-tracker-error';
export {
  AutoTranslationDisabledError,
  BaseLocaleImmutableError,
  BundleAlreadyExistsError,
  BundleNotFoundError,
  CannotTranslateBaseLocaleError,
  CollectionAlreadyExistsError,
  CollectionBaseLocaleMismatchError,
  CollectionNotFoundError,
  CollectionRenameBundleConflictError,
  CollectionRequiredByBundleError,
  ConfigChangedError,
  ConfigNotFoundError,
  ConfigParseError,
  CoreOperationError,
  FolderMoveIntoDescendantError,
  FolderNotFoundError,
  GlossaryExtractorError,
  GlossaryNoCollectionsError,
  ImportSourceError,
  InvalidBundleDefinitionError,
  InvalidBundleLocalesError,
  InvalidCollectionError,
  InvalidCollectionFolderError,
  InvalidConfigError,
  InvalidFolderPathError,
  InvalidImportLocaleError,
  InvalidLocaleError,
  InvalidNameError,
  InvalidProjectTermsEditError,
  isProtectedTermsEditProblem,
  isPreferredTerminologyEditProblem,
  type ProtectedTermsEditProblem,
  type PreferredTerminologyEditProblem,
  InvalidResourceKeyError,
  InvalidTranslationStatusError,
  LingoTrackerError,
  LocaleAlreadyExistsError,
  LocaleNotFoundError,
  MoveConfigRequiredError,
  MultipleBundleConstantNameError,
  NoTranslationTargetLocalesError,
  ParentDirectoryMissingError,
  PreferredTerminologyValidationError,
  ProtectedTermsFileError,
  ProtectedTermsFileNotSetError,
  ReadOnlyCollectionError,
  ResourceAlreadyExistsError,
  ResourceNotFoundError,
  TranslationError,
  TranslationLocaleNotConfiguredError,
} from './lingo-tracker-error';
